name: Build web-push vendor
on:
  workflow_dispatch:
  push:
    paths:
      - composer.json
      - composer.lock

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer

      - name: Cache composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Composer install (no-dev, optimized)
        run: |
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Upload vendor artifact
        uses: actions/upload-artifact@v4
        with:
          name: vendor
          path: vendor
